my_str = '我的名字叫 %s'  %('张三')
print(my_str)
my_str1 = '张三的年龄是 %d 岁' %(15)
print(my_str1)
my_str2 = '苹果的价格是 %f 元' %(5)
print(my_str2)
my_str3 = '今天星期{}，张三买了{}斤苹果'.format('三','3')
print(my_str3)
my_str4 = '张三今年{}岁'.format(26)
print(my_str4)
